### ISSUE TITLE
Disconnected whenever app goes in background state also what is gateway as I didn't find any.

### ISSUE THREAD

**Issue by pratyushpratiksinha** [voximplant/ios-sdk-swift-demo#4]
The app gets disconnected and below error comes

`2018-12-01 17:57:51.308025+0530 WizCounsel[6813:1579927] #VI/I [main-threa]:VIClient[LoggedIn] > disconnect
2018-12-01 17:57:51.309149+0530 WizCounsel[6813:1579973] #VI/I [sm        ]:VIAuthenticator[LoggedIn] > disconnect
2018-12-01 17:57:51.309468+0530 WizCounsel[6813:1579927] #VI/I [sm        ]:VIAuthenticator[LoggedIn] > webSocketDidCloseWithError: (null)
2018-12-01 17:57:51.310922+0530 WizCounsel[6813:1579750] #VI/I [main-threa]:VIClient[Disconnected] > required method -clientSessionDidDisconnect: called on <WizCounsel.VoxController: 0x129e27fa0>
2018-12-01 17:57:51.311622+0530 WizCounsel[6813:1579927] #SD/I [main-threa] Disconnected!
2018-12-01 17:57:51.312823+0530 WizCounsel[6813:1579927] #SD/D [main-threa] voxDidLoggedOut called on <WizCounsel.MainViewController: 0x12a1adc00>
2018-12-01 17:57:51.403886+0530 WizCounsel[6813:1579614] [Snapshotting] Snapshotting a view (0x12a918600, UIKeyboardImpl) that is not in a visible window requires afterScreenUpdates:YES.`

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for reaching out!

Due to iOS specific for the background mode, the connection to the Voximplant Cloud is closed once the application is in the background if there is no active calls at the moment. If there is an active call, the connection will be kept until the call is ended.

The logs that you provided are not error logs, they just show that the connection is closed.

Our demo application is implemented the way that the connection to the Voximplant Cloud is re-established once the application enters foreground. However I would like to notice that the logic to re-establish the connection in the foreground is implemented on application side, not on SDK side.

Enabling push notifications allows to receive the incoming calls when the application is in the background or closed, even it is not connected to the Voximplant Cloud. You can take a look at this article for details about Voximplant push notifications: https://voximplant.com/docs/references/iossdk/push-notifications-for-ios

Please let me know if you have any questions.

Best regards,
Yulia Grigorieva

**Comment by pratyushpratiksinha** [comment]
I am registering the application for push notification, still not receiving incoming call on background.

**Comment by pratyushpratiksinha** [comment]
![screenshot 2018-12-04 at 12 51 35 pm](https://user-images.githubusercontent.com/17877604/49425382-6c275300-f7c3-11e8-8eae-37c604a4ccd2.png)

**Comment by pratyushpratiksinha** [comment]
![screenshot 2018-12-04 at 12 52 55 pm](https://user-images.githubusercontent.com/17877604/49425423-8b25e500-f7c3-11e8-94a0-4b4c9dd71019.png)

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for provided information.

To diagnose the problem I recommend you check the call session logs. To do this, please follow the steps:
1. reproduce the issue
2. open the [Voximplant Control Panel](https://manage.voximplant.com)
3. Go to Calls -> Calls -> Find a call with the issue -> Click "View log" at the top right corner of the call details
4. Check that you have the following logs:
-  send push wakeup message:{"addr" : "<address>" , "callid" : "<call_id>" , "display_name" : "<display_name>" , "sessionid" : "<session_id>" , "userid" : "<user_id>"}
This log means that PushService is correctly connected in the scenario and push message is generated for the call
-  push wakeup result:<your_voximplant_user> {android={result=no tokens found}, ios={<your_push_token>={result=success}}}
This log represents the result of the push notification sending to APNS/Firebase. It should have your push token that is get on the device and provided via [registerPushNotificationsToken:imToken:](https://voximplant.com/docs/references/iossdk/viclient#registerpushnotificationstokenimtoken) API on the application side and the result. 
Result 'success' means that the push notification is successfully sent to APNS and it should be received on the device. If result is not 'success', it shows the error message.

Please check the call logs and let me know if there are any errors.

Best regards,
Yulia Grigorieva

**Comment by pratyushpratik** [comment]
push wakeup result: pratyushpratik@appcall.wizcounsel.voximplant.com > {android={result=no tokens found}, ios={8da93467e842d1702d37cb41162c059e0bbe885762d455e6b05e08cc44dbf798={result=reject : DeviceTokenNotForTopic}}}

I think this is the problem "{result=reject : DeviceTokenNotForTopic}". Can you please help me on this?

**Comment by pratyushpratiksinha** [comment]
push wakeup result: pratyushpratik@appcall.wizcounsel.voximplant.com > {android={result=no tokens found}, ios={xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx={result=reject : DeviceTokenNotForTopic}}}
Sent event to JS onPhoneEvent with params [{code = 480 ;  headers = {} ;  id = sGxkZu0oT6qqppXcZe-3l552TAR43EFUjqG7ZoxYgF4 ;  name = Call.Failed ;  reason = User offline ;  } ;  ]
2018-12-04 09:52:40 Terminating (onClose)
2018-12-04 09:52:40 Executing JS command: close with params [void ;  ]
2018-12-04 09:52:40 Normal termination
2018-12-04 09:52:40 Session terminated



I think this "{result=reject : DeviceTokenNotForTopic}" is the problem. Can you please help me on this?

**Comment by YuliaGrigorieva** [comment]
Hello!

This error generally means that the application bundle identifier does not match the bundle identifier for which push certificate was generated. Please check that bundle identifier is the same.

Best regards,
Yulia Grigorieva

**Comment by pratyushpratiksinha** [comment]
It means I have to add bundle identifier in voximplant same as Firebase, right?
If yes, I didn't find where to add the bundle identifier, please provide me the link or if there is any specific script for that please provide me.
Thanks in advance.

**Comment by YuliaGrigorieva** [comment]
I meant that bundle id in the Xcode project should match the bundle id of the application for which the push certificate was created.
Please take a look at these screenshots:
- Bundle id in the Xcode project:
<img width="1179" alt="screenshot 2018-12-04 at 14 02 15" src="https://user-images.githubusercontent.com/8545374/49437997-199f6400-f7ce-11e8-86ca-1676de822f5c.png">

- Select the same bundle id in the apple account while creating the push certificate:
<img width="700" alt="screenshot 2018-12-04 at 14 05 11" src="https://user-images.githubusercontent.com/8545374/49438067-45bae500-f7ce-11e8-9486-ed3d22a7f21f.png">

These bundle identifiers should be the same.

Best regards,
Yulia Grigorieva

**Comment by pratyushpratiksinha** [comment]
I checked it once again, now I am getting error.
"push wakeup result: wiz007@appcall.wizcounsel.voximplant.com > {android={result=no tokens found}, ios={xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx={result=error : Internal error}}}"

**Comment by YuliaGrigorieva** [comment]
Please check that you have created a "VoIP Services" certificate, but not "Apple Development iOS Push Services" certificate. To check this, open Keychain Access on your mac, double click on the certificate that you added to the Voximplant Control Panel and ensure that it is "VoIP Services" certificate.
<img width="700" alt="screenshot 2018-12-04 at 15 55 37" src="https://user-images.githubusercontent.com/8545374/49443397-6474a800-f7dd-11e8-988c-ee15f6b03a25.png">

Also, it seems that you added a production push certificate instead of development. The difference is that production certificates work only with builds from AppStore or TestFlight, if you build and test the application from Xcode, you need to add the certificate as "Development" in the Voximplant Control Panel.

Best regards,
Yulia Grigorieva

**Comment by rajngarg** [comment]
Hello @YuliaGrigorieva ,
I am getting this in xcode logs
VIClient[Disconnected] > Using bundleId: (null) 

I think due to which push token is not generated and also getting this

[RNVoipPushNotificationManager] getVoIPPushToken: token is null

I will be very thankful to you.
