### ISSUE TITLE
[Question] where can I get credentials for your demo? 

### ISSUE THREAD

**Issue by astrokin** [voximplant/ios-sdk-swift-demo#8]
where can I get credentials for your demo? do you have any sample test server to play with?

**Comment by VladimirBrejcha** [comment]
Hey,

In order to work with our platform Voximplant developer account needed.

For manual setup, at least two users, a simple scenario and a route should be created there. More info about basic concepts of Voximplant in [introduction](https://voximplant.com/docs/introduction/introduction_to_voximplant/basic_concepts)

Another option, is to just install [SDK tutorial](https://manage.voximplant.com/marketplace/sdk_tutorial) from our marketplace
